apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
      name: dingo-apm
spec:
    version: 7.12.1
    count: 1
    elasticsearchRef:
        name: dingo
    kibanaRef:
        name: dingo-kbn
    podTemplate:
        metadata:
            labels:
                apm: "on"
        spec:
            containers:
            - name: apm-server
              resources:
                  requests:
                      memory: 4Gi
                      cpu: 1400m
                  limits:
                      memory: 4Gi
                      cpu: 1400m
